import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Canary Training 1",
            artist: "30:00",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-8.png",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%201%20-canario-timbrado-espanol_entrenamiento-campeones-2017.mp3",
            active: true,
        },
        {
            name:"Canary Training 2",
            artist: "44:39",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-9.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%202%20-canario-timbrado-espanol-entrenamiento-canto-campeon-internacional-2018.mp3",
            active: false,
        },
        {
            name:"Canary Training 3",
            artist: "32:46",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-20.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%203%20-canary-singing-most-spectacular-4k-video-training.mp3",
            active: false,
        },
        {
            name:"Canary Training 4",
            artist: "38:37",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario13.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%204%20-canario-belga-salsa-2.mp3",
            active: false,
        },
        {
            name:"Canary Training 5",
            artist: "35:50",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-23.png",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: " https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%205%20-canario-timbrado-espanol-cd-entrenamiento-190-points.mp3",
            active: false,
        },
        {
            name:"Canary Training 6",
            artist: "27:10",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-22.png",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%206%20-best-canary-singing-on-youtube-4k.mp3",
            active: false,
        },
        {
            name:"Canary Training 7",
            artist: "30:36",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-21.png",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%207-canario-belga-cantando-muito-para-esquentar-machos.mp3",
            active: false,
        },
        {
            name:"Canary Training 8",
            artist: "20:00",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-19.png",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%208%20-canario-belga-raiden-cantando-muito-esquente-seu-canario-belga-03.mp3",
            active: false,
        },
        {
            name:"Canary Training 9",
            artist: "30:31",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-15.png",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%209%20-canario-belga-salsa-cantando-muito-forte.mp3",
            active: false,
        },
        {
            name:"Canary Training 10",
            artist: "30:57",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-17.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2010%20-canario-belga-salsa-estourado-esquente-em-30-minutos.mp3",
            active: false,
        },
        {
            name:"Canary Training 11",
            artist: "39:42",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-18.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2011%20-canario-do-reino-belga-canto-para-treinar-filhotes.mp3",
            active: false,
        },
        {
            name:"Canary Training 12",
            artist: "33:30",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-10.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2012%20-canary-singing-most-spectacular-video-training-make-your-canary-singing-like-champion.mp3",
            active: false,
        },
        {
            name:"Canary Training 13",
            artist: "40:46",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-14.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2013%20-canary-singing-video-the-best-canary-training-song-40-minutes.mp3",
            active: false,
        },
        {
            name:"Canary Training 14",
            artist: "29:19",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-7.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2014%20-canary-s-most-powerful-song-for-training.mp3",
            active: false,
        },
        {
            name:"Canary Training 15",
            artist: "31:39",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-2.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2015%20-esquente-seu-canario-belga-em-30-minutos-canario-belga-estourado.mp3",
            active: false,
        },
        {
            name:"Canary Training 16",
            artist: "31:21",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-1.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2016%20-esquente-seu-canario-belga-em-30-minutos-canario-pastinha-cantando.mp3",
            active: false,
        },
        {
            name:"Canary Training 17",
            artist: "40:02",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-22.1.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2017%20-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito.mp3",
            active: false,
        },
        {
            name:"Canary Training 18",
            artist: "30:26",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-6.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2018%20-pancingan-ampuh-untuk-burung-malas-bunyi.mp3",
            active: false,
        },
        {
            name:"Canary Training 19",
            artist: "47:04",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-21.png",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://ia902507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2019%20-tghryd-knary-km-alabdaaa-ltsmyaa-alfrakh.mp3",
            active: false,
        },
        {
            name:"Canary Training 20",
            artist: "40:23",
            cover: "https://manuappshome.files.wordpress.com/2020/01/canario-9.png",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://ia802507.us.archive.org/31/items/canary-training-17-esquente-seu-filhote-e-canario-belga-em-30-minutos-macho-cantando-muito/Canary%20Training%2020%20-tghryd-taer-knary-jbar-yhfz-althkr-oyhyj-alanthy-ltzaoj-km-alabdaaa-ltsmyaa-alfrakh-canto-do-canario.mp3",
            active: false,
        },
    ];
}

export default chillHop;

